version: "3.9"

services:
  wordpress:
    image: wordpress
    build: .
    ports:
      - "8080:80"
    networks:
      - overlay
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PASSWORD=postgres
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
      
  mysql:
    image: mysql
    volumes:
       - db-data:/var/lib/mysql/data
    networks:
       - overlay
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr
      placement:
        constraints:
          - "node.role==manager"

volumes:
  db-data:

networks:
  overlay:
